export const Regioes = {
    CHAPADA_VALE_DO_RIO_ITAIM: 'Chapada Vale do Rio Itaim',
    ENTRE_RIOS: 'Entre Rios',
    VALE_DO_RIO_GUARIBAS: 'Vale do Rio Guaribas',
    CHAPADA_DAS_MANGABEIRAS: 'Chapada das Mangabeiras',
    SERRA_DA_CAPIVARA: 'Serra da Capivara',
    TABULEIROS_DO_ALTO_PARNAIBA: 'Tabuleiros do Alto Parnaíba',
    VALE_DO_SAMBITO: 'Vale do Sambito',
    VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS: 'Vale dos Rios Piauí e Itaueiras',
    CARNAUBAIS: 'Carnaubais',
    COCAIS: 'Cocais',
    VALE_DO_CANINDE: 'Vale do Canindé',
    PLANICIE_LITORANEA: 'Planície Litorânea'
  };

export const FaixaPopulacional = {
    MENOS_DE_5000_HABITANTES: 'Até 5.000 habitantes',
    DE_5001_A_10000_HABITANTES: 'De 5.001 a 10.000 habitantes',
    DE_10001_A_20000_HABITANTES: 'De 10.001 a 20.000 habitantes',
    DE_20001_A_50000_HABITANTES: 'De 20.001 a 50.000 habitantes',
    ACIMA_DE_50000_HABITANTES: 'Acima de 50.000 habitantes'
  };

export const municipios = {
  '2200053': {
    nomeMunicipio: 'Acauã',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 6420,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2200103': {
    nomeMunicipio: 'Agricolândia',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 4940,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2200202': {
    nomeMunicipio: 'Água Branca',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 17573,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2200251': {
    nomeMunicipio: 'Alagoinha do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 6819,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2200277': {
    nomeMunicipio: 'Alegrete do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 4634,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2200301': {
    nomeMunicipio: 'Alto Longá',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 13479,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2200400': {
    nomeMunicipio: 'Altos',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 47453,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2200459': {
    nomeMunicipio: 'Alvorada do Gurguéia',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 5322,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2200509': {
    nomeMunicipio: 'Amarante',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 17234,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2200608': {
    nomeMunicipio: 'Angical do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 6827,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2200707': {
    nomeMunicipio: 'Anísio de Abreu',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 9407,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2200806': {
    nomeMunicipio: 'Antônio Almeida',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 3152,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2200905': {
    nomeMunicipio: 'Aroazes',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '7',
    populacao: 5369,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2200954': {
    nomeMunicipio: 'Aroeiras do Itaim',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 2690,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2201002': {
    nomeMunicipio: 'Arraial',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '21',
    gerencia: '6',
    populacao: 4520,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2201051': {
    nomeMunicipio: 'Assunção do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 7452,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201101': {
    nomeMunicipio: 'Avelino Lopes',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 10866,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2201150': {
    nomeMunicipio: 'Baixa Grande do Ribeiro',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 13272,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2201176': {
    nomeMunicipio: "Barra D'Alcântara",
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 3995,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2201200': {
    nomeMunicipio: 'Barras',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 47938,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2201309': {
    nomeMunicipio: 'Barreiras do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 3264,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2201408': {
    nomeMunicipio: 'Barro Duro',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '18',
    populacao: 6640,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201507': {
    nomeMunicipio: 'Batalha',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 26300,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2201556': {
    nomeMunicipio: 'Bela Vista do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '12',
    populacao: 4091,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2201572': {
    nomeMunicipio: 'Belém do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 3423,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2201606': {
    nomeMunicipio: 'Beneditinos',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '18',
    populacao: 9929,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201705': {
    nomeMunicipio: 'Bertolínia',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '11',
    populacao: 5562,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201739': {
    nomeMunicipio: 'Betânia do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 6220,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201770': {
    nomeMunicipio: 'Boa Hora',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '2',
    populacao: 6902,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201804': {
    nomeMunicipio: 'Bocaina',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 4078,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2201903': {
    nomeMunicipio: 'Bom Jesus',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 28796,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2201919': {
    nomeMunicipio: 'Bom Princípio do Piauí',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 5636,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201929': {
    nomeMunicipio: 'Bonfim do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 5913,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201945': {
    nomeMunicipio: 'Boqueirão do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 6545,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201960': {
    nomeMunicipio: 'Brasileira',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 8436,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2201988': {
    nomeMunicipio: 'Brejo do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '12',
    populacao: 3904,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202000': {
    nomeMunicipio: 'Buriti dos Lopes',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 19654,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2202026': {
    nomeMunicipio: 'Buriti dos Montes',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 7434,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202059': {
    nomeMunicipio: 'Cabeceiras do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '2',
    populacao: 10212,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2202075': {
    nomeMunicipio: 'Cajazeiras do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 3108,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202083': {
    nomeMunicipio: 'Cajueiro da Praia',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '1',
    gerencia: '1',
    populacao: 7957,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202091': {
    nomeMunicipio: 'Caldeirão Grande do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 5503,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202109': {
    nomeMunicipio: 'Campinas do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '8',
    populacao: 4938,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202117': {
    nomeMunicipio: 'Campo Alegre do Fidalgo',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '12',
    populacao: 4616,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202133': {
    nomeMunicipio: 'Campo Grande do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '9',
    populacao: 6020,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202174': {
    nomeMunicipio: 'Campo Largo do Piauí',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 7419,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202208': {
    nomeMunicipio: 'Campo Maior',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 45793,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2202251': {
    nomeMunicipio: 'Canavieira',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 3414,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202307': {
    nomeMunicipio: 'Canto do Buriti',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '12',
    populacao: 19365,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2202406': {
    nomeMunicipio: 'Capitão de Campos',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '3',
    populacao: 11100,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2202455': {
    nomeMunicipio: 'Capitão Gervásio Oliveira',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '12',
    populacao: 3974,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202505': {
    nomeMunicipio: 'Caracol',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 10318,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2202539': {
    nomeMunicipio: 'Caraúbas do Piauí',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 5630,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202554': {
    nomeMunicipio: 'Caridade do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 5033,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202604': {
    nomeMunicipio: 'Castelo do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 19288,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2202653': {
    nomeMunicipio: 'Caxingó',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '14',
    populacao: 5496,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202703': {
    nomeMunicipio: 'Cocal',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 28212,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2202711': {
    nomeMunicipio: 'Cocal de Telha',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '1',
    populacao: 4911,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202729': {
    nomeMunicipio: 'Cocal dos Alves',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 6386,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202737': {
    nomeMunicipio: 'Coivaras',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 4117,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202752': {
    nomeMunicipio: 'Colônia do Gurguéia',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '10',
    populacao: 6150,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202778': {
    nomeMunicipio: 'Colônia do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 6994,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2202802': {
    nomeMunicipio: 'Conceição do Canindé',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '17',
    populacao: 4932,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202851': {
    nomeMunicipio: 'Coronel José Dias',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 4250,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2202901': {
    nomeMunicipio: 'Corrente',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 27278,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2203008': {
    nomeMunicipio: 'Cristalândia do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 7283,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2203107': {
    nomeMunicipio: 'Cristino Castro',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 10503,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2203206': {
    nomeMunicipio: 'Curimatá',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 11270,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2203230': {
    nomeMunicipio: 'Currais',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 4844,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2203271': {
    nomeMunicipio: 'Curral Novo do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 5073,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2203255': {
    nomeMunicipio: 'Curralinhos',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '18',
    populacao: 4413,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2203305': {
    nomeMunicipio: 'Demerval Lobão',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '18',
    populacao: 16352,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2203354': {
    nomeMunicipio: 'Dirceu Arcoverde',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 7054,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2203404': {
    nomeMunicipio: 'Dom Expedito Lopes',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 6320,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2203453': {
    nomeMunicipio: 'Dom Inocêncio',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 9159,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2203420': {
    nomeMunicipio: 'Domingos Mourão',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 4075,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2203503': {
    nomeMunicipio: 'Elesbão Veloso',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 13607,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2203602': {
    nomeMunicipio: 'Eliseu Martins',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '10',
    populacao: 4377,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2203701': {
    nomeMunicipio: 'Esperantina',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 40970,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2203750': {
    nomeMunicipio: 'Fartura do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 5284,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2203800': {
    nomeMunicipio: 'Flores do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '10',
    populacao: 4414,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2203859': {
    nomeMunicipio: 'Floresta do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '8',
    populacao: 2333,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2203909': {
    nomeMunicipio: 'Floriano',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '21',
    gerencia: '10',
    populacao: 62036,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '2204006': {
    nomeMunicipio: 'Francinópolis',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 4505,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2204105': {
    nomeMunicipio: 'Francisco Ayres',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '21',
    gerencia: '6',
    populacao: 4412,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2204154': {
    nomeMunicipio: 'Francisco Macedo',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 2929,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2204204': {
    nomeMunicipio: 'Francisco Santos',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '9',
    populacao: 8237,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2204303': {
    nomeMunicipio: 'Fronteiras',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 10259,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2204352': {
    nomeMunicipio: 'Geminiano',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 5445,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2204402': {
    nomeMunicipio: 'Gilbués',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 10892,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2204501': {
    nomeMunicipio: 'Guadalupe',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 10270,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2204550': {
    nomeMunicipio: 'Guaribas',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 4276,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2204600': {
    nomeMunicipio: 'Hugo Napoleão',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 3518,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2204659': {
    nomeMunicipio: 'Ilha Grande',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '1',
    gerencia: '1',
    populacao: 9274,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2204709': {
    nomeMunicipio: 'Inhuma',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 14958,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2204808': {
    nomeMunicipio: 'Ipiranga do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '9',
    populacao: 9420,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2204907': {
    nomeMunicipio: 'Isaías Coelho',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '8',
    populacao: 7774,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205003': {
    nomeMunicipio: 'Itainópolis',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 10790,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2205102': {
    nomeMunicipio: 'Itaueira',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '10',
    populacao: 10323,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2205151': {
    nomeMunicipio: 'Jacobina do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 5624,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205201': {
    nomeMunicipio: 'Jaicós',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '9',
    populacao: 4180,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205250': {
    nomeMunicipio: 'Jardim do Mulato',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 4494,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205276': {
    nomeMunicipio: 'Jatobá do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 4497,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205300': {
    nomeMunicipio: 'Jerumenha',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 17527,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2205359': {
    nomeMunicipio: 'João Costa',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '12',
    populacao: 2970,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205409': {
    nomeMunicipio: 'Joaquim Pires',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 13886,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2205458': {
    nomeMunicipio: 'Joca Marques',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 5394,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205508': {
    nomeMunicipio: 'José de Freitas',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 42559,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2205516': {
    nomeMunicipio: 'Juazeiro do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 5214,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205524': {
    nomeMunicipio: 'Júlio Borges',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 5388,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205532': {
    nomeMunicipio: 'Jurema',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 4425,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205557': {
    nomeMunicipio: 'Lagoa Alegre',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 8256,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205573': {
    nomeMunicipio: 'Lagoa de São Francisco',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '12',
    populacao: 6331,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205565': {
    nomeMunicipio: 'Lagoa do Barro do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '18',
    populacao: 4995,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205581': {
    nomeMunicipio: 'Lagoa do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '3',
    populacao: 4810,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205599': {
    nomeMunicipio: 'Lagoa do Sítio',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 4520,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205540': {
    nomeMunicipio: 'Lagoinha do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 2939,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2205607': {
    nomeMunicipio: 'Landri Sales',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 5213,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205706': {
    nomeMunicipio: 'Luís Correia',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '1',
    gerencia: '1',
    populacao: 30641,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2205805': {
    nomeMunicipio: 'Luzilândia',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 25375,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2205854': {
    nomeMunicipio: 'Madeiro',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 8032,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205904': {
    nomeMunicipio: 'Manoel Emídio',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '10',
    populacao: 5209,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2205953': {
    nomeMunicipio: 'Marcolândia',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 8533,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206001': {
    nomeMunicipio: 'Marcos Parente',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 4724,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2206050': {
    nomeMunicipio: 'Massapê do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '9',
    populacao: 5218,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206100': {
    nomeMunicipio: 'Matias Olímpio',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 10641,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2206209': {
    nomeMunicipio: 'Miguel Alves',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 32150,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2206308': {
    nomeMunicipio: 'Miguel Leão',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '6',
    populacao: 1318,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2206357': {
    nomeMunicipio: 'Milton Brandão',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 6542,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206407': {
    nomeMunicipio: 'Monsenhor Gil',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '18',
    populacao: 10255,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2206506': {
    nomeMunicipio: 'Monsenhor Hipólito',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '9',
    populacao: 7577,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206605': {
    nomeMunicipio: 'Monte Alegre do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 10660,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2206654': {
    nomeMunicipio: 'Morro Cabeça no Tempo',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 4377,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2206670': {
    nomeMunicipio: 'Morro do Chapéu do Piauí',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 6425,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206696': {
    nomeMunicipio: 'Murici dos Portelas',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 9797,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206704': {
    nomeMunicipio: 'Nazaré do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '21',
    gerencia: '10',
    populacao: 6665,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206720': {
    nomeMunicipio: 'Nazária',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 10262,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2206753': {
    nomeMunicipio: 'Nossa Senhora de Nazaré',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 5228,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206803': {
    nomeMunicipio: 'Nossa Senhora dos Remédios',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 8525,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2207959': {
    nomeMunicipio: 'Nova Santa Rita',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 4076,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2206902': {
    nomeMunicipio: 'Novo Oriente do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 6097,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2206951': {
    nomeMunicipio: 'Novo Santo Antônio',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '18',
    populacao: 2827,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207009': {
    nomeMunicipio: 'Oeiras',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 38138,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2207108': {
    nomeMunicipio: "Olho D'Água do Piauí",
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 2637,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207207': {
    nomeMunicipio: 'Padre Marcos',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 6382,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2207306': {
    nomeMunicipio: 'Paes Landim',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 4088,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207355': {
    nomeMunicipio: 'Pajeú do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '12',
    populacao: 3000,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207405': {
    nomeMunicipio: 'Palmeira do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 4952,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207504': {
    nomeMunicipio: 'Palmeirais',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '18',
    populacao: 13264,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2207553': {
    nomeMunicipio: 'Paquetá',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 3813,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207603': {
    nomeMunicipio: 'Parnaguá',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 10103,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2207702': {
    nomeMunicipio: 'Parnaíba',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '1',
    gerencia: '1',
    populacao: 162159,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '2207751': {
    nomeMunicipio: 'Passagem Franca do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '18',
    populacao: 4135,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207777': {
    nomeMunicipio: 'Patos do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 5425,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2207793': {
    nomeMunicipio: "Pau D'Arco do Piauí",
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 3880,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207801': {
    nomeMunicipio: 'Paulistana',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 21055,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2207850': {
    nomeMunicipio: 'Pavussu',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '10',
    populacao: 3628,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2207900': {
    nomeMunicipio: 'Pedro II',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 37894,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2207934': {
    nomeMunicipio: 'Pedro Laurentino',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 2458,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2208007': {
    nomeMunicipio: 'Picos',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 83090,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '2208106': {
    nomeMunicipio: 'Pimenteiras',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 11341,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2208205': {
    nomeMunicipio: 'Pio IX',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 17613,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2208304': {
    nomeMunicipio: 'Piracuruca',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 28846,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2208403': {
    nomeMunicipio: 'Piripiri',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 65538,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '2208502': {
    nomeMunicipio: 'Porto',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 12052,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2208551': {
    nomeMunicipio: 'Porto Alegre do Piauí',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '11',
    populacao: 2364,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2208601': {
    nomeMunicipio: 'Prata do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '18',
    populacao: 3042,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2208650': {
    nomeMunicipio: 'Queimada Nova',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 8738,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2208700': {
    nomeMunicipio: 'Redenção do Gurguéia',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '14',
    populacao: 8394,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2208809': {
    nomeMunicipio: 'Regeneração',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 17133,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2208858': {
    nomeMunicipio: 'Riacho Frio',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 4165,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2208874': {
    nomeMunicipio: 'Ribeira do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 4055,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2208908': {
    nomeMunicipio: 'Ribeiro Gonçalves',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 6164,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209005': {
    nomeMunicipio: 'Rio Grande do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '10',
    populacao: 5801,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209104': {
    nomeMunicipio: 'Santa Cruz do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '9',
    populacao: 5831,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209153': {
    nomeMunicipio: 'Santa Cruz dos Milagres',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '7',
    populacao: 3435,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209203': {
    nomeMunicipio: 'Santa Filomena',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 6087,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209302': {
    nomeMunicipio: 'Santa Luz',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 5336,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209377': {
    nomeMunicipio: 'Santa Rosa do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 4650,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209351': {
    nomeMunicipio: 'Santana do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 4125,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209401': {
    nomeMunicipio: 'Santo Antônio de Lisboa',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 5839,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209450': {
    nomeMunicipio: 'Santo Antônio dos Milagres',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 2138,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209500': {
    nomeMunicipio: 'Santo Inácio do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '8',
    populacao: 3646,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209559': {
    nomeMunicipio: 'São Braz do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 4358,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209609': {
    nomeMunicipio: 'São Félix do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '7',
    populacao: 2842,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209658': {
    nomeMunicipio: 'São Francisco de Assis do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '17',
    populacao: 5572,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209708': {
    nomeMunicipio: 'São Francisco do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '10',
    populacao: 5392,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209757': {
    nomeMunicipio: 'São Gonçalo do Gurguéia',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 2947,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209807': {
    nomeMunicipio: 'São Gonçalo do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 4837,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209856': {
    nomeMunicipio: 'São João da Canabrava',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 4242,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209872': {
    nomeMunicipio: 'São João da Fronteira',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 5552,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209906': {
    nomeMunicipio: 'São João da Serra',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 6114,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2209955': {
    nomeMunicipio: 'São João da Varjota',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 4383,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2209971': {
    nomeMunicipio: 'São João do Arraial',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 8186,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2210003': {
    nomeMunicipio: 'São João do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '12',
    populacao: 21421,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2210052': {
    nomeMunicipio: 'São José do Divino',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 4841,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210102': {
    nomeMunicipio: 'São José do Peixe',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '10',
    populacao: 3297,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210201': {
    nomeMunicipio: 'São José do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 6597,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2210300': {
    nomeMunicipio: 'São Julião',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 6025,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2210359': {
    nomeMunicipio: 'São Lourenço do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 4410,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210375': {
    nomeMunicipio: 'São Luis do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 2309,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210383': {
    nomeMunicipio: 'São Miguel da Baixa Grande',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '7',
    populacao: 2269,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210391': {
    nomeMunicipio: 'São Miguel do Fidalgo',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '8',
    populacao: 2829,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210409': {
    nomeMunicipio: 'São Miguel do Tapuio',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 17554,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2210508': {
    nomeMunicipio: 'São Pedro do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 13755,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2210607': {
    nomeMunicipio: 'São Raimundo Nonato',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 38934,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2210623': {
    nomeMunicipio: 'Sebastião Barros',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 3202,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210631': {
    nomeMunicipio: 'Sebastião Leal',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 4446,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210656': {
    nomeMunicipio: 'Sigefredo Pacheco',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 9460,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2210706': {
    nomeMunicipio: 'Simões',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 14350,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2210805': {
    nomeMunicipio: 'Simplício Mendes',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '12',
    populacao: 13870,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '2210904': {
    nomeMunicipio: 'Socorro do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 4141,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210938': {
    nomeMunicipio: 'Sussuapara',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 6220,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2210953': {
    nomeMunicipio: 'Tamboril do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '12',
    populacao: 2949,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2210979': {
    nomeMunicipio: 'Tanque do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 2316,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2211001': {
    nomeMunicipio: 'Teresina',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '4, 19, 20, 21',
    populacao: 866300,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '2211100': {
    nomeMunicipio: 'União',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 46119,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2211209': {
    nomeMunicipio: 'Uruçuí',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 25203,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2211308': {
    nomeMunicipio: 'Valença do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 22279,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '2211357': {
    nomeMunicipio: 'Várzea Branca',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 5055,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '2211407': {
    nomeMunicipio: 'Várzea Grande',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 4417,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2211506': {
    nomeMunicipio: 'Vera Mendes',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 3185,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2211605': {
    nomeMunicipio: 'Vila Nova do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 2935,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '2211704': {
    nomeMunicipio: 'Wall Ferraz',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '9',
    populacao: 4059,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
};
