export const columnNameMap = {
  ANO: "Ano",

  // Indicador 1: Local de Funcionamento
  IN_LOCAL_FUNC_PREDIO_ESCOLAR: "Funciona em Prédio Escolar",
  TP_OCUPACAO_PREDIO_ESCOLAR: "Tipo Ocupação Prédio Escolar",
  IN_LOCAL_FUNC_SALAS_EMPRESA: "Funciona em Salas de Empresa",
  IN_LOCAL_FUNC_SOCIOEDUCATIVO: "Funciona em Unidade Socioeducativa",
  IN_LOCAL_FUNC_UNID_PRISIONAL: "Funciona em Unidade Prisional",
  IN_LOCAL_FUNC_PRISIONAL_SOCIO: "Funciona em Prisional/Socioeducativo",
  IN_LOCAL_FUNC_TEMPLO_IGREJA: "Funciona em Templo/Igreja",
  IN_LOCAL_FUNC_CASA_PROFESSOR: "Funciona na Casa do Professor",
  IN_LOCAL_FUNC_GALPAO: "Funciona em Galpão",
  TP_OCUPACAO_GALPAO: "Tipo Ocupação Galpão",
  IN_LOCAL_FUNC_SALAS_OUTRA_ESC: "Funciona em Outra Escola",
  IN_LOCAL_FUNC_OUTROS: "Funciona em Outro Local",
  IN_PREDIO_COMPARTILHADO: "Prédio Compartilhado",

  // Indicador 2: Infraestrutura Básica
  IN_AGUA_POTAVEL: "Água Potável",
  IN_AGUA_FILTRADA: "Água Filtrada",
  IN_AGUA_REDE_PUBLICA: "Água da Rede Pública",
  IN_AGUA_POCO_ARTESIANO: "Água de Poço Artesiano",
  IN_AGUA_CACIMBA: "Água de Cacimba",
  IN_AGUA_FONTE_RIO: "Água de Rio/Fonte",
  IN_AGUA_INEXISTENTE: "Sem Água",
  IN_AGUA_CARRO_PIPA: "Água por Carro-Pipa",
  IN_ENERGIA_REDE_PUBLICA: "Energia da Rede Pública",
  IN_ENERGIA_GERADOR: "Energia por Gerador",
  IN_ENERGIA_GERADOR_FOSSIL: "Energia Gerador Fóssil",
  IN_ENERGIA_RENOVAVEL: "Energia Renovável",
  IN_ENERGIA_OUTROS: "Energia Outros",
  IN_ENERGIA_INEXISTENTE: "Sem Energia",
  IN_ESGOTO_REDE_PUBLICA: "Esgoto na Rede Pública",
  IN_ESGOTO_FOSSA: "Esgoto em Fossa",
  IN_ESGOTO_FOSSA_SEPTICA: "Fossa Séptica",
  IN_ESGOTO_FOSSA_COMUM: "Fossa Comum",
  IN_ESGOTO_INEXISTENTE: "Sem Esgoto",
  IN_LIXO_SERVICO_COLETA: "Coleta de Lixo",
  IN_LIXO_QUEIMA: "Lixo Queimado",
  IN_LIXO_ENTERRA: "Lixo Enterrado",
  IN_LIXO_DESTINO_FINAL_PUBLICO: "Destino Final Público",
  IN_LIXO_JOGA_OUTRA_AREA: "Lixo em Outra Área",
  IN_LIXO_DESCARTA_OUTRA_AREA: "Descarta em Outra Área",
  IN_LIXO_RECICLA: "Recicla Lixo",
  IN_LIXO_OUTROS: "Outros Destinos de Lixo",
  IN_TRATAMENTO_LIXO_SEPARACAO: "Separação de Lixo",
  IN_TRATAMENTO_LIXO_REUTILIZA: "Reutilização de Lixo",
  IN_TRATAMENTO_LIXO_RECICLAGEM: "Reciclagem de Lixo",
  IN_TRATAMENTO_LIXO_INEXISTENTE: "Sem Tratamento de Lixo",
  IN_BANHEIRO: "Tem Banheiro",
  IN_BANHEIRO_FORA_PREDIO: "Banheiro Fora do Prédio",
  IN_BANHEIRO_DENTRO_PREDIO: "Banheiro Dentro do Prédio",
  IN_BANHEIRO_PNE: "Banheiro Acessível (PNE)",
  IN_BANHEIRO_EI: "Banheiro para Educação Infantil",
  IN_BANHEIRO_FUNCIONARIOS: "Banheiro para Funcionários",
  IN_BANHEIRO_CHUVEIRO: "Tem Chuveiro",
  IN_DEPENDENCIAS_PNE: "Dependências PNE",
  IN_ACESSIBILIDADE_INEXISTENTE: "Sem Acessibilidade",
  IN_ACESSIBILIDADE_CORRIMAO: "Corrimão",
  IN_ACESSIBILIDADE_ELEVADOR: "Elevador",
  IN_ACESSIBILIDADE_PISOS_TATEIS: "Pisos Táteis",
  IN_ACESSIBILIDADE_VAO_LIVRE: "Vão Livre",
  IN_ACESSIBILIDADE_RAMPAS: "Rampas",
  IN_ACESSIBILIDADE_SINAL_SONORO: "Sinal Sonoro",
  IN_ACESSIBILIDADE_SINAL_TATIL: "Sinal Tátil",
  IN_ACESSIBILIDADE_SINAL_VISUAL: "Sinal Visual",

  // Espaços pedagógicos e equipamentos (indicador 3)
  IN_BIBLIOTECA_SALA_LEITURA: "Biblioteca / Sala de Leitura",
  IN_BIBLIOTECA: "Biblioteca",
  IN_SALA_LEITURA: "Sala de Leitura",
  IN_COZINHA: "Cozinha",
  IN_LABORATORIO_CIENCIAS: "Laboratório de Ciências",
  IN_LABORATORIO_INFORMATICA: "Laboratório de Informática",
  IN_LABORATORIO_EDUC_PROF: "Laboratório Educação Profissional",
  IN_QUADRA_ESPORTES_COBERTA: "Quadra Coberta",
  IN_QUADRA_ESPORTES_DESCOBERTA: "Quadra Descoberta",
  IN_QUADRA_ESPORTES: "Quadra de Esportes",
  IN_SALA_ATENDIMENTO_ESPECIAL: "Sala Atendimento Especial",
  IN_AUDITORIO: "Auditório",
  IN_PATIO_COBERTO: "Pátio Coberto",
  IN_PATIO_DESCOBERTO: "Pátio Descoberto",
  IN_PISCINA: "Piscina",
  IN_SALA_DIRETORIA: "Sala da Diretoria",
  IN_SALA_PROFESSOR: "Sala dos Professores",
  IN_SALA_SECRETARIA: "Sala da Secretaria",
  IN_REFEITORIO: "Refeitório",
  IN_ALMOXARIFADO: "Almoxarifado",
  IN_DESPENSA: "Despensa",
  IN_AREA_VERDE: "Área Verde",
  IN_BERCARIO: "Berçário",
  IN_DORMITORIO_ALUNO: "Dormitório Aluno",
  IN_PARQUE_INFANTIL: "Parque Infantil",
  IN_SALA_ATELIE_ARTES: "Ateliê / Artes",
  IN_SALA_MUSICA_CORAL: "Sala Música / Coral",
  IN_SALA_ESTUDIO_DANCA: "Sala Estúdio Dança",
  IN_SALA_MULTIUSO: "Sala Multiuso",
  IN_SALA_ESTUDIO_GRAVACAO: "Sala Estúdio Gravação",
  IN_SALA_OFICINAS_EDUC_PROF: "Sala Oficinas Educação Profissional",
  IN_SALA_REPOUSO_ALUNO: "Sala de Repouso",
  IN_TERREIRAO: "Terreiro",
  IN_VIVEIRO: "Viveiro",
  QT_SALAS_EXISTENTES: "Qtd. Salas Existentes",
  QT_SALAS_UTILIZADAS: "Qtd. Salas Utilizadas",
  QT_SALAS_UTILIZADAS_DENTRO: "Qtd. Salas Utilizadas Dentro",
  QT_SALAS_UTILIZADAS_FORA: "Qtd. Salas Utilizadas Fora",
  QT_SALAS_UTILIZA_CLIMATIZADAS: "Qtd. Salas Climatizadas",
  QT_SALAS_UTILIZADAS_ACESSIVEIS: "Qtd. Salas Acessíveis",
  
  // Equipamentos
  IN_EQUIP_TV: "Possui TV",
  IN_EQUIP_VIDEOCASSETE: "Possui Videocassete",
  IN_EQUIP_DVD: "Possui DVD",
  IN_EQUIP_PARABOLICA: "Possui Antena Parabólica",
  IN_EQUIP_COPIADORA: "Possui Copiadora",
  IN_EQUIP_RETROPROJETOR: "Possui Retroprojetor",
  IN_EQUIP_IMPRESSORA: "Possui Impressora",
  IN_EQUIP_IMPRESSORA_MULT: "Possui Impressora Multiplicadora",
  IN_EQUIP_SOM: "Possui Som",
  IN_EQUIP_PROJETOR: "Possui Projetor",
  IN_EQUIP_MULTIMIDIA: "Possui Multimídia",
  IN_EQUIP_FAX: "Possui Fax",
  IN_EQUIP_FOTO: "Possui Câmera Fotográfica",
  IN_EQUIP_SCANNER: "Possui Scanner",
  IN_EQUIP_NENHUM: "Não Possui Equipamentos",
  IN_EQUIP_LOUSA_DIGITAL: "Possui Lousa Digital",
  QT_EQUIP_TV: "Qtd. TVs",
  QT_EQUIP_VIDEOCASSETE: "Qtd. Videocassetes",
  QT_EQUIP_DVD: "Qtd. DVDs",
  QT_EQUIP_PARABOLICA: "Qtd. Antenas Parabólicas",
  QT_EQUIP_COPIADORA: "Qtd. Copiadoras",
  QT_EQUIP_RETROPROJETOR: "Qtd. Retroprojetores",
  QT_EQUIP_IMPRESSORA: "Qtd. Impressoras",
  QT_EQUIP_IMPRESSORA_MULT: "Qtd. Impressoras Multiplicadoras",
  QT_EQUIP_SOM: "Qtd. Equipamentos de Som",
  QT_EQUIP_PROJETOR: "Qtd. Projetores",
  QT_EQUIP_MULTIMIDIA: "Qtd. Equipamentos Multimídia",
  QT_EQUIP_FAX: "Qtd. Fax",
  QT_EQUIP_FOTO: "Qtd. Câmeras Fotográficas",
  QT_EQUIP_LOUSA_DIGITAL: "Qtd. Lousas Digitais",

  // Computadores / Internet
  IN_COMPUTADOR: "Possui Computadores",
  QT_COMPUTADOR: "Qtd. Computadores",
  QT_COMP_ADMINISTRATIVO: "Qtd. Computadores Administrativo",
  QT_COMP_ALUNO: "Qtd. Computadores Aluno",
  IN_DESKTOP_ALUNO: "Possui Desktop para Aluno",
  QT_DESKTOP_ALUNO: "Qtd. Desktops Aluno",
  IN_COMP_PORTATIL_ALUNO: "Possui Computador Portátil para Aluno",
  QT_COMP_PORTATIL_ALUNO: "Qtd. Computadores Portáteis",
  IN_TABLET_ALUNO: "Possui Tablet para Aluno",
  QT_TABLET_ALUNO: "Qtd. Tablets Aluno",
  IN_INTERNET: "Possui Internet",
  IN_INTERNET_APRENDIZAGEM: "Internet para Aprendizagem",
  IN_INTERNET_ADMINISTRATIVO: "Internet Administrativa",
  IN_INTERNET_ALUNOS: "Internet para Alunos",
  IN_INTERNET_COMUNIDADE: "Internet para Comunidade",
  IN_ACESSO_INTERNET_COMPUTADOR: "Acesso à Internet pelo Computador",
  IN_ACESSO_INTERNET_DISP_PESSOAIS: "Acesso à Internet em Dispositivos Pessoais",
  TP_REDE_LOCAL: "Tipo de Rede Local",
  IN_BANDA_LARGA: "Possui Banda Larga",

  // Materiais
  IN_MATERIAL_ESP_NAO_UTILIZA: "Não Utiliza Materiais Específicos",
  IN_MATERIAL_ESP_PEDAGOGICO: "Materiais Pedagógicos",
  IN_MATERIAL_ESP_ARTES: "Materiais de Artes",
  IN_MATERIAL_ESP_AUDIOVISUAIS: "Materiais Audiovisuais",
  IN_MATERIAL_ESP_AUDITIVOS: "Materiais Auditivos",
  IN_MATERIAL_ESP_BIOLOGIA: "Materiais Biologia",
  IN_MATERIAL_ESP_BRINQUEDOS: "Brinquedos",
  IN_MATERIAL_ESP_CIENCIAS: "Materiais de Ciências",
  IN_MATERIAL_ESP_CINEMA: "Materiais de Cinema",
  IN_MATERIAL_ESP_DISCIPLINAR: "Materiais Disciplinares",
  IN_MATERIAL_ESP_FISICA: "Materiais Física",
  IN_MATERIAL_ESP_FOTO: "Materiais Fotográficos",
  IN_MATERIAL_ESP_INFORMATICA: "Materiais Informática",
  IN_MATERIAL_ESP_JOGOS: "Materiais de Jogos",
  IN_MATERIAL_ESP_JORNAIS: "Jornais",
  IN_MATERIAL_ESP_LIVROS_DIDAT: "Livros Didáticos",
  IN_MATERIAL_ESP_LIVROS_LITER: "Livros Literários",
  IN_MATERIAL_ESP_MAPAS: "Mapas",
  IN_MATERIAL_ESP_MUSICA: "Materiais Música",
  IN_MATERIAL_ESP_OUTROS: "Materiais Outros",
  IN_MATERIAL_ESP_QUIMICA: "Materiais Química",
  IN_MATERIAL_ESP_REVISTAS: "Revistas",
  IN_MATERIAL_ESP_QUILOMBOLA: "Materiais Quilombola",
  IN_MATERIAL_ESP_INDIGENA: "Materiais Indígena",

  // Outros Campos
  IN_ALIMENTACAO: "Tem Alimentação",
  IN_ATIV_COMPLEMENTAR: "Tem Atividade Complementar",
  IN_FUNDEB: "Recebe Fundeb",
  TP_DEPENDENCIA: "Tipo de Dependência",
  TP_LOCALIZACAO: "Localização",
  CO_MUNICIPIO: "Código Município",
  NO_MUNICIPIO: "Município",
  CO_UF: "Código UF",
  SG_UF: "UF",
  NO_ENTIDADE: "Nome da Entidade",
  N_MATERIAL_PED_INFANTIL: "Materiais Pedagógicos Infantis",
  IN_MATERIAL_PED_CIENTIFICO: "Materiais Científicos",
  IN_MATERIAL_PED_DIFUSAO: "Materiais de Difusão",
  IN_MATERIAL_PED_MUSICAL: "Materiais Musicais",
  IN_MATERIAL_PED_JOGOS: "Jogos Educativos",
  IN_MATERIAL_PED_ARTISTICAS: "Materiais Artísticos",
  IN_MATERIAL_PED_PROFISSIONAL: "Materiais Profissionais",
  IN_MATERIAL_PED_DESPORTIVA: "Materiais Esportivos",
  IN_MATERIAL_PED_INDIGENA: "Materiais Indígenas",
  IN_MATERIAL_PED_ETNICO: "Materiais Étnicos",
  IN_MATERIAL_PED_CAMPO: "Materiais do Campo",
  IN_MATERIAL_PED_BIL_SURDOS: "Materiais Bilíngues para Surdos",
  IN_MATERIAL_PED_QUILOMBOLA: "Materiais Quilombolas",
  IN_MATERIAL_PED_AGRICOLA: "Materiais Agrícolas",
  IN_MATERIAL_PED_EDU_ESP: "Materiais de Educação Especial",
  IN_MATERIAL_PED_NENHUM: "Sem Materiais Pedagógicos",

  // Modalidades e Classes
  IN_REGULAR_CLASSE_COMUM: "Classe Comum - Regular",
  IN_REGULAR_CLASSE_ESP: "Classe Especial - Regular",
  IN_ESP_CLASSE_COMUM: "Classe Comum - Educação Especial",
  IN_ESP_CLASSE_ESP: "Classe Especial - Educação Especial",
  IN_EJA_CLASSE_COMUM: "Classe Comum - EJA",
  IN_EJA_CLASSE_ESP: "Classe Especial - EJA",

  // Línguas Indígenas
  CO_LINGUA_INDIGENA_1: "Língua Indígena 1",
  CO_LINGUA_INDIGENA_2: "Língua Indígena 2",
  CO_LINGUA_INDIGENA_3: "Língua Indígena 3",

  // Estrutura e Dependências
  IN_AREA_PLANTIO: "Área de Plantio",
  IN_DEPENDENCIAS_OUTRAS: "Outras Dependências",
  IN_DORMITORIO_PROFESSOR: "Dormitório de Professores",
  IN_EDUCACAO_INDIGENA: "Educação Indígena",
  IN_LAVANDERIA: "Lavanderia",

  // Atendimento Educacional Especializado (AEE)
  TP_AEE: "Tipo de Atendimento Educacional Especializado",
  TP_ATIVIDADE_COMPLEMENTAR: "Atividade Complementar",
  TP_INDIGENA_LINGUA: "Tipo de Língua Indígena",

  // Mediação
  IN_MEDIACAO_PRESENCIAL: "Mediado Presencialmente",
  IN_MEDIACAO_SEMIPRESENCIAL: "Mediado Semipresencialmente",
  IN_MEDIACAO_EAD: "Mediado a Distância (EAD)",

  // Infraestrutura
  IN_QUADRA_ESPORTES_PNE: "Quadra Esportiva Acessível",
  IN_SANITARIO_PNE: "Sanitário Acessível",
  IN_SANITARIO: "Sanitário",
  IN_SANITARIO_FORA_PREDIO: "Sanitário Fora do Prédio",
  IN_SANITARIO_DENTRO_PREDIO: "Sanitário Dentro do Prédio",
  IN_SANITARIO_CHUVEIRO: "Sanitário com Chuveiro",

  // Professores
  IN_PROF_CLASSE_COMUM: "Professor em Classe Comum",
  IN_PROF_CLASSE_ESP: "Professor em Classe Especial",
};