export const Regioes = {
    CHAPADA_VALE_DO_RIO_ITAIM: 'CHAPADA VALE DO RIO ITAIM',
    ENTRE_RIOS: 'ENTRE RIOS',
    VALE_DO_RIO_GUARIBAS: 'VALE DO RIO GUARIBAS',
    CHAPADA_DAS_MANGABEIRAS: 'CHAPADA DAS MANGABEIRAS',
    SERRA_DA_CAPIVARA: 'SERRA DA CAPIVARA',
    TABULEIROS_DO_ALTO_PARNAIBA: 'TABULEIROS DO ALTO PARNAIBA',
    VALE_DO_SAMBITO: 'VALE DO SAMBITO',
    VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS: 'VALE DOS RIOS PIAUI E ITAUEIRAS',
    CARNAUBAIS: 'CARNAUBAIS',
    COCAIS: 'COCAIS',
    VALE_DO_CANINDE: 'VALE DO CANINDE',
    PLANICIE_LITORANEA: 'PLANICIE LITORANEA'
  };

export  const FaixaPopulacional = {
    MENOS_DE_5000_HABITANTES: 'MENOS DE 5000 HABITANTES',
    DE_5001_A_10000_HABITANTES: 'DE 5001 A 10000 HABITANTES',
    DE_10001_A_20000_HABITANTES: 'DE 10001 A 20000 HABITANTES',
    DE_20001_A_50000_HABITANTES: 'DE 20001 A 50000 HABITANTES',
    ACIMA_DE_50000_HABITANTES: 'ACIMA DE 50000 HABITANTES'
  };

export const municipios = {
  '220010': {
    nomeMunicipio: 'Agricolândia',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 4940,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220020': {
    nomeMunicipio: 'Água Branca',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 17573,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220025': {
    nomeMunicipio: 'Alagoinha do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 6819,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220027': {
    nomeMunicipio: 'Alegrete do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 4634,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220030': {
    nomeMunicipio: 'Alto Longá',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 13479,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220040': {
    nomeMunicipio: 'Altos',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 47453,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220045': {
    nomeMunicipio: 'Alvorada do Gurguéia',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 5322,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220050': {
    nomeMunicipio: 'Amarante',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 17234,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220060': {
    nomeMunicipio: 'Angical do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 6827,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220070': {
    nomeMunicipio: 'Anísio de Abreu',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 9407,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220080': {
    nomeMunicipio: 'Antônio Almeida',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 3152,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220090': {
    nomeMunicipio: 'Aroazes',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '7',
    populacao: 5369,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220095': {
    nomeMunicipio: 'Aroeiras do Itaim',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 2690,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220100': {
    nomeMunicipio: 'Arraial',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '21',
    gerencia: '6',
    populacao: 4520,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220105': {
    nomeMunicipio: 'Assunção do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 7452,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220110': {
    nomeMunicipio: 'Avelino Lopes',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 10866,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220115': {
    nomeMunicipio: 'Baixa Grande do Ribeiro',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 13272,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220117': {
    nomeMunicipio: "Barra D'Alcântara",
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 3995,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220120': {
    nomeMunicipio: 'Barras',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 47938,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220130': {
    nomeMunicipio: 'Barreiras do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 3264,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220140': {
    nomeMunicipio: 'Barro Duro',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '18',
    populacao: 6640,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220150': {
    nomeMunicipio: 'Batalha',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 26300,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220155': {
    nomeMunicipio: 'Bela Vista do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '12',
    populacao: 4091,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220157': {
    nomeMunicipio: 'Belém do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 3423,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220160': {
    nomeMunicipio: 'Beneditinos',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '18',
    populacao: 9929,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220170': {
    nomeMunicipio: 'Bertolínia',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '11',
    populacao: 5562,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220173': {
    nomeMunicipio: 'Betânia do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 6220,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220177': {
    nomeMunicipio: 'Boa Hora',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '2',
    populacao: 6902,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220180': {
    nomeMunicipio: 'Bocaina',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 4078,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220190': {
    nomeMunicipio: 'Bom Jesus',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 28796,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220191': {
    nomeMunicipio: 'Bom Princípio do Piauí',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 5636,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220192': {
    nomeMunicipio: 'Bonfim do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 5913,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220194': {
    nomeMunicipio: 'Boqueirão do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 6545,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220196': {
    nomeMunicipio: 'Brasileira',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 8436,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220198': {
    nomeMunicipio: 'Brejo do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '12',
    populacao: 3904,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220200': {
    nomeMunicipio: 'Buriti dos Lopes',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 19654,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220202': {
    nomeMunicipio: 'Buriti dos Montes',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 7434,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220205': {
    nomeMunicipio: 'Cabeceiras do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '2',
    populacao: 10212,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220207': {
    nomeMunicipio: 'Cajazeiras do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 3108,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220208': {
    nomeMunicipio: 'Cajueiro da Praia',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '1',
    gerencia: '1',
    populacao: 7957,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220209': {
    nomeMunicipio: 'Caldeirão Grande do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 5503,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220210': {
    nomeMunicipio: 'Campinas do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '8',
    populacao: 4938,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220211': {
    nomeMunicipio: 'Campo Alegre do Fidalgo',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '12',
    populacao: 4616,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220213': {
    nomeMunicipio: 'Campo Grande do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '9',
    populacao: 6020,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220217': {
    nomeMunicipio: 'Campo Largo do Piauí',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 7419,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220220': {
    nomeMunicipio: 'Campo Maior',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 45793,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220225': {
    nomeMunicipio: 'Canavieira',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 3414,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220230': {
    nomeMunicipio: 'Canto do Buriti',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '12',
    populacao: 19365,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220240': {
    nomeMunicipio: 'Capitão de Campos',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '3',
    populacao: 11100,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220245': {
    nomeMunicipio: 'Capitão Gervásio Oliveira',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '12',
    populacao: 3974,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220250': {
    nomeMunicipio: 'Caracol',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 10318,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220253': {
    nomeMunicipio: 'Caraúbas do Piauí',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 5630,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220255': {
    nomeMunicipio: 'Caridade do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 5033,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220260': {
    nomeMunicipio: 'Castelo do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 19288,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220265': {
    nomeMunicipio: 'Caxingó',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '14',
    populacao: 5496,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220270': {
    nomeMunicipio: 'Cocal',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 28212,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220271': {
    nomeMunicipio: 'Cocal de Telha',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '1',
    populacao: 4911,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220272': {
    nomeMunicipio: 'Cocal dos Alves',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 6386,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220273': {
    nomeMunicipio: 'Coivaras',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 4117,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220275': {
    nomeMunicipio: 'Colônia do Gurguéia',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '10',
    populacao: 6150,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220277': {
    nomeMunicipio: 'Colônia do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 6994,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220280': {
    nomeMunicipio: 'Conceição do Canindé',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '17',
    populacao: 4932,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220285': {
    nomeMunicipio: 'Coronel José Dias',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 4250,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220290': {
    nomeMunicipio: 'Corrente',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 27278,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220300': {
    nomeMunicipio: 'Cristalândia do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 7283,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220310': {
    nomeMunicipio: 'Cristino Castro',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 10503,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220320': {
    nomeMunicipio: 'Curimatá',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 11270,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220323': {
    nomeMunicipio: 'Currais',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 4844,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220327': {
    nomeMunicipio: 'Curral Novo do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 5073,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220325': {
    nomeMunicipio: 'Curralinhos',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '18',
    populacao: 4413,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220330': {
    nomeMunicipio: 'Demerval Lobão',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '18',
    populacao: 16352,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220335': {
    nomeMunicipio: 'Dirceu Arcoverde',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 7054,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220340': {
    nomeMunicipio: 'Dom Expedito Lopes',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 6320,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220345': {
    nomeMunicipio: 'Dom Inocêncio',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 9159,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220342': {
    nomeMunicipio: 'Domingos Mourão',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 4075,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220350': {
    nomeMunicipio: 'Elesbão Veloso',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 13607,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220360': {
    nomeMunicipio: 'Eliseu Martins',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '10',
    populacao: 4377,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220370': {
    nomeMunicipio: 'Esperantina',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 40970,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220375': {
    nomeMunicipio: 'Fartura do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 5284,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220380': {
    nomeMunicipio: 'Flores do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '10',
    populacao: 4414,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220385': {
    nomeMunicipio: 'Floresta do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '8',
    populacao: 2333,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220390': {
    nomeMunicipio: 'Floriano',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '21',
    gerencia: '10',
    populacao: 62036,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '220400': {
    nomeMunicipio: 'Francinópolis',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 4505,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220410': {
    nomeMunicipio: 'Francisco Ayres',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '21',
    gerencia: '6',
    populacao: 4412,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220415': {
    nomeMunicipio: 'Francisco Macedo',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 2929,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220420': {
    nomeMunicipio: 'Francisco Santos',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '9',
    populacao: 8237,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220430': {
    nomeMunicipio: 'Fronteiras',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 10259,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220435': {
    nomeMunicipio: 'Geminiano',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 5445,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220440': {
    nomeMunicipio: 'Gilbués',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 10892,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220450': {
    nomeMunicipio: 'Guadalupe',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 10270,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220455': {
    nomeMunicipio: 'Guaribas',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 4276,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220460': {
    nomeMunicipio: 'Hugo Napoleão',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 3518,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220465': {
    nomeMunicipio: 'Ilha Grande',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '1',
    gerencia: '1',
    populacao: 9274,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220470': {
    nomeMunicipio: 'Inhuma',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 14958,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220480': {
    nomeMunicipio: 'Ipiranga do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '9',
    populacao: 9420,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220490': {
    nomeMunicipio: 'Isaías Coelho',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '8',
    populacao: 7774,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220500': {
    nomeMunicipio: 'Itainópolis',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 10790,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220510': {
    nomeMunicipio: 'Itaueira',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '10',
    populacao: 10323,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220515': {
    nomeMunicipio: 'Jacobina do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 5624,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220520': {
    nomeMunicipio: 'Jaicós',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '9',
    populacao: 4180,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220525': {
    nomeMunicipio: 'Jardim do Mulato',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 4494,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220527': {
    nomeMunicipio: 'Jatobá do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 4497,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220530': {
    nomeMunicipio: 'Jerumenha',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 17527,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220535': {
    nomeMunicipio: 'João Costa',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '12',
    populacao: 2970,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220540': {
    nomeMunicipio: 'Joaquim Pires',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 13886,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220545': {
    nomeMunicipio: 'Joca Marques',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 5394,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220550': {
    nomeMunicipio: 'José de Freitas',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 42559,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220551': {
    nomeMunicipio: 'Juazeiro do Piauí',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 5214,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220552': {
    nomeMunicipio: 'Júlio Borges',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 5388,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220553': {
    nomeMunicipio: 'Jurema',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 4425,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220555': {
    nomeMunicipio: 'Lagoa Alegre',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 8256,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220557': {
    nomeMunicipio: 'Lagoa de São Francisco',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '12',
    populacao: 6331,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220556': {
    nomeMunicipio: 'Lagoa do Barro do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '18',
    populacao: 4995,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220558': {
    nomeMunicipio: 'Lagoa do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '3',
    populacao: 4810,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220559': {
    nomeMunicipio: 'Lagoa do Sítio',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 4520,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220554': {
    nomeMunicipio: 'Lagoinha do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 2939,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220560': {
    nomeMunicipio: 'Landri Sales',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 5213,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220570': {
    nomeMunicipio: 'Luís Correia',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '1',
    gerencia: '1',
    populacao: 30641,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220580': {
    nomeMunicipio: 'Luzilândia',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 25375,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220585': {
    nomeMunicipio: 'Madeiro',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 8032,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220590': {
    nomeMunicipio: 'Manoel Emídio',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '10',
    populacao: 5209,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220595': {
    nomeMunicipio: 'Marcolândia',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 8533,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220600': {
    nomeMunicipio: 'Marcos Parente',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '10',
    populacao: 4724,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220605': {
    nomeMunicipio: 'Massapê do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '9',
    populacao: 5218,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220610': {
    nomeMunicipio: 'Matias Olímpio',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 10641,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220620': {
    nomeMunicipio: 'Miguel Alves',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 32150,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220630': {
    nomeMunicipio: 'Miguel Leão',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '6',
    populacao: 1318,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220635': {
    nomeMunicipio: 'Milton Brandão',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 6542,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220640': {
    nomeMunicipio: 'Monsenhor Gil',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '8',
    gerencia: '18',
    populacao: 10255,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220650': {
    nomeMunicipio: 'Monsenhor Hipólito',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '9',
    populacao: 7577,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220660': {
    nomeMunicipio: 'Monte Alegre do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 10660,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220665': {
    nomeMunicipio: 'Morro Cabeça no Tempo',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 4377,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220667': {
    nomeMunicipio: 'Morro do Chapéu do Piauí',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 6425,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220669': {
    nomeMunicipio: 'Murici dos Portelas',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '2',
    gerencia: '1',
    populacao: 9797,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220670': {
    nomeMunicipio: 'Nazaré do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '21',
    gerencia: '10',
    populacao: 6665,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220672': {
    nomeMunicipio: 'Nazária',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 10262,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220675': {
    nomeMunicipio: 'Nossa Senhora de Nazaré',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 5228,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220680': {
    nomeMunicipio: 'Nossa Senhora dos Remédios',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 8525,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220795': {
    nomeMunicipio: 'Nova Santa Rita',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 4076,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220690': {
    nomeMunicipio: 'Novo Oriente do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 6097,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220695': {
    nomeMunicipio: 'Novo Santo Antônio',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '18',
    populacao: 2827,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220700': {
    nomeMunicipio: 'Oeiras',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 38138,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220710': {
    nomeMunicipio: "Olho D'Água do Piauí",
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 2637,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220720': {
    nomeMunicipio: 'Padre Marcos',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 6382,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220730': {
    nomeMunicipio: 'Paes Landim',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 4088,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220735': {
    nomeMunicipio: 'Pajeú do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '12',
    populacao: 3000,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220740': {
    nomeMunicipio: 'Palmeira do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 4952,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220750': {
    nomeMunicipio: 'Palmeirais',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '18',
    populacao: 13264,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220755': {
    nomeMunicipio: 'Paquetá',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 3813,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220760': {
    nomeMunicipio: 'Parnaguá',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '15',
    populacao: 10103,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220770': {
    nomeMunicipio: 'Parnaíba',
    territorioDesenvolvimento: Regioes.PLANICIE_LITORANEA,
    aglomerado: '1',
    gerencia: '1',
    populacao: 162159,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '220775': {
    nomeMunicipio: 'Passagem Franca do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '18',
    populacao: 4135,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220777': {
    nomeMunicipio: 'Patos do Piauí',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 5425,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220779': {
    nomeMunicipio: "Pau D'Arco do Piauí",
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 3880,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220780': {
    nomeMunicipio: 'Paulistana',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 21055,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220785': {
    nomeMunicipio: 'Pavussu',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '10',
    populacao: 3628,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220790': {
    nomeMunicipio: 'Pedro II',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 37894,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220793': {
    nomeMunicipio: 'Pedro Laurentino',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 2458,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220800': {
    nomeMunicipio: 'Picos',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 83090,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '220810': {
    nomeMunicipio: 'Pimenteiras',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 11341,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220820': {
    nomeMunicipio: 'Pio IX',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 17613,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220830': {
    nomeMunicipio: 'Piracuruca',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 28846,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '220840': {
    nomeMunicipio: 'Piripiri',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 65538,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '220850': {
    nomeMunicipio: 'Porto',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 12052,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220855': {
    nomeMunicipio: 'Porto Alegre do Piauí',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '24',
    gerencia: '11',
    populacao: 2364,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220860': {
    nomeMunicipio: 'Prata do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '18',
    populacao: 3042,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220865': {
    nomeMunicipio: 'Queimada Nova',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '14',
    gerencia: '17',
    populacao: 8738,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220870': {
    nomeMunicipio: 'Redenção do Gurguéia',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '27',
    gerencia: '14',
    populacao: 8394,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220880': {
    nomeMunicipio: 'Regeneração',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 17133,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '220885': {
    nomeMunicipio: 'Riacho Frio',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 4165,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220887': {
    nomeMunicipio: 'Ribeira do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 4055,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220890': {
    nomeMunicipio: 'Ribeiro Gonçalves',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 6164,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220900': {
    nomeMunicipio: 'Rio Grande do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '10',
    populacao: 5801,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220910': {
    nomeMunicipio: 'Santa Cruz do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '9',
    populacao: 5831,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220915': {
    nomeMunicipio: 'Santa Cruz dos Milagres',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '7',
    populacao: 3435,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220920': {
    nomeMunicipio: 'Santa Filomena',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 6087,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220930': {
    nomeMunicipio: 'Santa Luz',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '26',
    gerencia: '14',
    populacao: 5336,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220937': {
    nomeMunicipio: 'Santa Rosa do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 4650,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220935': {
    nomeMunicipio: 'Santana do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 4125,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220940': {
    nomeMunicipio: 'Santo Antônio de Lisboa',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 5839,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220945': {
    nomeMunicipio: 'Santo Antônio dos Milagres',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 2138,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220950': {
    nomeMunicipio: 'Santo Inácio do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '8',
    populacao: 3646,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220955': {
    nomeMunicipio: 'São Braz do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 4358,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220960': {
    nomeMunicipio: 'São Félix do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '7',
    populacao: 2842,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220965': {
    nomeMunicipio: 'São Francisco de Assis do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '17',
    populacao: 5572,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220970': {
    nomeMunicipio: 'São Francisco do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '10',
    populacao: 5392,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220975': {
    nomeMunicipio: 'São Gonçalo do Gurguéia',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 2947,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220980': {
    nomeMunicipio: 'São Gonçalo do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 4837,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220985': {
    nomeMunicipio: 'São João da Canabrava',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 4242,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220987': {
    nomeMunicipio: 'São João da Fronteira',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 5552,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220990': {
    nomeMunicipio: 'São João da Serra',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 6114,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '220995': {
    nomeMunicipio: 'São João da Varjota',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 4383,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '220997': {
    nomeMunicipio: 'São João do Arraial',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '3',
    gerencia: '2',
    populacao: 8186,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '221000': {
    nomeMunicipio: 'São João do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '18',
    gerencia: '12',
    populacao: 21421,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '221005': {
    nomeMunicipio: 'São José do Divino',
    territorioDesenvolvimento: Regioes.COCAIS,
    aglomerado: '4',
    gerencia: '3',
    populacao: 4841,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221010': {
    nomeMunicipio: 'São José do Peixe',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '10',
    populacao: 3297,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221020': {
    nomeMunicipio: 'São José do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 6597,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '221030': {
    nomeMunicipio: 'São Julião',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 6025,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '221035': {
    nomeMunicipio: 'São Lourenço do Piauí',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 4410,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221037': {
    nomeMunicipio: 'São Luis do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 2309,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221038': {
    nomeMunicipio: 'São Miguel da Baixa Grande',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '10',
    gerencia: '7',
    populacao: 2269,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221039': {
    nomeMunicipio: 'São Miguel do Fidalgo',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '8',
    populacao: 2829,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221040': {
    nomeMunicipio: 'São Miguel do Tapuio',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '6',
    gerencia: '5',
    populacao: 17554,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '221050': {
    nomeMunicipio: 'São Pedro do Piauí',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '9',
    gerencia: '6',
    populacao: 13755,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '221060': {
    nomeMunicipio: 'São Raimundo Nonato',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '20',
    gerencia: '13',
    populacao: 38934,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '221062': {
    nomeMunicipio: 'Sebastião Barros',
    territorioDesenvolvimento: Regioes.CHAPADA_DAS_MANGABEIRAS,
    aglomerado: '28',
    gerencia: '15',
    populacao: 3202,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221063': {
    nomeMunicipio: 'Sebastião Leal',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 4446,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221065': {
    nomeMunicipio: 'Sigefredo Pacheco',
    territorioDesenvolvimento: Regioes.CARNAUBAIS,
    aglomerado: '5',
    gerencia: '5',
    populacao: 9460,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '221070': {
    nomeMunicipio: 'Simões',
    territorioDesenvolvimento: Regioes.CHAPADA_VALE_DO_RIO_ITAIM,
    aglomerado: '13',
    gerencia: '16',
    populacao: 14350,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '221080': {
    nomeMunicipio: 'Simplício Mendes',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '17',
    gerencia: '12',
    populacao: 13870,
    faixaPopulacional: FaixaPopulacional.DE_10001_A_20000_HABITANTES,
  },
  '221090': {
    nomeMunicipio: 'Socorro do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '22',
    gerencia: '12',
    populacao: 4141,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221093': {
    nomeMunicipio: 'Sussuapara',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 6220,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '221095': {
    nomeMunicipio: 'Tamboril do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DOS_RIOS_PIAUI_E_ITAUEIRAS,
    aglomerado: '23',
    gerencia: '12',
    populacao: 2949,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221097': {
    nomeMunicipio: 'Tanque do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '8',
    populacao: 2316,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221100': {
    nomeMunicipio: 'Teresina',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '4, 19, 20, 21',
    populacao: 866300,
    faixaPopulacional: FaixaPopulacional.ACIMA_DE_50000_HABITANTES,
  },
  '221110': {
    nomeMunicipio: 'União',
    territorioDesenvolvimento: Regioes.ENTRE_RIOS,
    aglomerado: '7',
    gerencia: '18',
    populacao: 46119,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '221120': {
    nomeMunicipio: 'Uruçuí',
    territorioDesenvolvimento: Regioes.TABULEIROS_DO_ALTO_PARNAIBA,
    aglomerado: '25',
    gerencia: '11',
    populacao: 25203,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '221130': {
    nomeMunicipio: 'Valença do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 22279,
    faixaPopulacional: FaixaPopulacional.DE_20001_A_50000_HABITANTES,
  },
  '221135': {
    nomeMunicipio: 'Várzea Branca',
    territorioDesenvolvimento: Regioes.SERRA_DA_CAPIVARA,
    aglomerado: '19',
    gerencia: '13',
    populacao: 5055,
    faixaPopulacional: FaixaPopulacional.DE_5001_A_10000_HABITANTES,
  },
  '221140': {
    nomeMunicipio: 'Várzea Grande',
    territorioDesenvolvimento: Regioes.VALE_DO_SAMBITO,
    aglomerado: '11',
    gerencia: '7',
    populacao: 4417,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221150': {
    nomeMunicipio: 'Vera Mendes',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '12',
    gerencia: '9',
    populacao: 3185,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221160': {
    nomeMunicipio: 'Vila Nova do Piauí',
    territorioDesenvolvimento: Regioes.VALE_DO_RIO_GUARIBAS,
    aglomerado: '15',
    gerencia: '16',
    populacao: 2935,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
  '221170': {
    nomeMunicipio: 'Wall Ferraz',
    territorioDesenvolvimento: Regioes.VALE_DO_CANINDE,
    aglomerado: '16',
    gerencia: '9',
    populacao: 4059,
    faixaPopulacional: FaixaPopulacional.MENOS_DE_5000_HABITANTES,
  },
};
