export const mapOwnRevenues = {
  "IPTU": ["RECEITA_RESULTANTE_IMPOSTO_IPTU", "IPTU_RECEITA_RESULTANTE", "RECEITA_IPTU", "RECEITA_RESULTANTE_DO_IPTU"],
  "ITBI": ["ITBI_RECEITA_RESULTANTE", "RECEITA_ITBI", "RECEITA_RESULTANTE_ITBI", "RECEITA_RESULTANTE_DO_ITBI"],
  "ISS": ["RECEITA_ISS", "ISS_RECEITA_RESULTANTE", "RECEITA_RESULTANTE_ISS", "RECEITA_RESULTANTE_DO_ISS"],
  "IRRF": ["IRRF_RECEITA_RESULTANTE", "RECEITA_RESULTANTE_IRRF", "RECEITA_IRRF", "RECEITA_RESULTANTE_DO_IRRF"],
  "ITR": ["ITR_RECEITA_RESULTANTE"],
  "TOTAL": ["RECEITAS_DE_IMPOSTO", "RECEITAS_DE_IMPOSTOS", "RECEITA_DE_IMPOSTOS"]
};

export const mapConstitutionalTransfersRevenue = {
  "FPM": ["FPM", "COTA_PARTE_FPM", "COTA_PARTE_FPE"],
  "Cota parte ICMS": ["COTA_PARTE_ICMS"],
  "ICMS Desoneração LC87/96": ["ICMS_DESONERACAO", "ICMS_DESONERACAO_LC_87_1996"],
  "Cota parte IPI-Exp": ["IPI_EXPORTACAO", "COTA_PARTE_IPI_EXPORTACAO"],
  "Cota-parte ITR": ["COTA_PARTE_ITR_100_PORCENTO", "COTA_PARTE_ITR"],
  "Cota-parte IPVA": ["COTA_PARTE_IPVA", "COTA_PARTE_IPVA_100_PORCENTO"],
  "Cota-parte IOF-Ouro": ["COTA_PARTE_IOF_OURO_100_PORCENTO", "COTA_PARTE_IOF_OURO"],
  "Outras transferências e compensações financeiras de impostos e transferências constitucionais": ["COMPENSACOES_FINANCEIRAS", "OUTRAS_TRANSFERENCIAS_IMPOSTOS_E_TRANSFERENCIAS_CONSTITUCIONAIS"],
  "TOTAL": ["RECEITAS_DE_TRANSFERENCIAS_CONSTITUCIONAIS_E_LEGAL", "RECEITA_DE_TRANSFERENCIAS_CONSTITUCIONAIS_E_LEGAIS", "RECEITA_TRANSFERENCIAS_CONSTITUCIONAIS"]
}

export const mapMunicipalTaxesRevenues = {
  "Receita líquida de impostos próprios": ["RECEITAS_DE_IMPOSTO", "RECEITA_DE_IMPOSTOS", "RECEITAS_DE_IMPOSTOS"],
  "Receita líquida de transferências constitucionais federais (FPM, IPI-EXP, IOF-Ouro, ICMS desoneração)": [
    "RECEITAS_DE_TRANSFERENCIAS_CONSTITUCIONAIS_E_LEGAL",
    "RECEITA_DE_TRANSFERENCIAS_CONSTITUCIONAIS_E_LEGAIS",
    "RECEITA_TRANSFERENCIAS_CONSTITUCIONAIS"
  ],
  "TOTAL": ["RECEITA_RESULTANTE_DE_IMPOSTOS", "TOTAL_RECEITA_BRUTA_IMPOSTOS", "TOTAL_RECEITA_IMPOSTOS", "TOTAL_DA_RECEITA_RESULTANTE_DE_IMPOSTOS"]
};

export const mapAdditionalMunicipalEducationRevenue = {
  "Salário-Educação": ["TRANSFERENCIAS_DO_SALARIO_EDUCACAO", "TRANSFERENCIAS_SALARIO_EDUCACAO", "FIN_ENSINO_SALARIO_EDUCACAO", "RECEITA_DE_TRANSFERENCIAS_DO_FNDE_SALARIO_EDUCACAO"],
  "Outras transferências do FNDE": [
    "OUTRAS_TRANSFERENCIAS_DO_FNDE",
    "OUTRAS_TRANSFERENCIAS_FNDE",
    "FIN_ENSINO_OUTRAS_TRANSFERENCIAS_FNDE",
    "RECEITA_DE_TRANSFERENCIAS_DO_FNDE_OUTRAS_TRANSFERENCIAS"
  ],
  "Aplicação financeira dos recursos do FNDE": ["APLICACAO_FINANCEIRA_FNDE"],
  "PDDE": ["TRANSFERENCIAS_DIRETAS_PDDE", "FIN_ENSINO_PDDE", "RECEITA_DE_TRANSFERENCIAS_DO_FNDE_PDDE"],
  "PNAE": ["TRANSFERENCIAS_DIRETAS_PNAE", "FIN_ENSINO_PNAE", "RECEITA_DE_TRANSFERENCIAS_DO_FNDE_PNAE"],
  "PNATE": ["FIN_ENSINO_PNATE", "TRANSFERENCIAS_DIRETAS_PNATE", "RECEITA_DE_TRANSFERENCIAS_DO_FNDE_PNATE"],
  "Convênios": [
    "TRANSFERENCIAS_DESTINADAS_A_PROGRAMAS_DE_EDUCACAO",
    "TRANSFERENCIAS_CONVENIOS_PROGRAMAS_EDUCACAO",
    "TRANSFERENCIAS_CONVENIOS",
    "FIN_ENSINO_RECEITA_TRANSFERENCIAS_CONVENIOS",
    "RECEITA_DE_TRANSFERENCIAS_DE_CONVENIOS"
  ],
  "Operação de créditos": [
    "RECEITA_DE_OPERACOES_DE_CREDITO_DESTINADAS_A_EDUCACAO",
    "RECEITA_OPERACOES_CREDITO_DESTINADA_EDUCACAO",
    "RECEITA_OPERACOES_CREDITO",
    "FIN_ENSINO_RECEITA_OPERACOES_CREDITO_EDUCACAO",
    "RECEITA_DE_OPERACOES_DE_CREDITO_VINCULADAS_A_EDUCACAO"
  ],
  "Royalties": ["FIN_ENSINO_RECEITA_ROYALTIES_DESTINADOS_EDUCACAO", "RECEITA_DE_ROYALTIES_DESTINADOS_A_EDUCACAO"],
  "Outras receitas": ["FIN_ENSINO_OUTRAS_RECEITAS", "OUTRAS_RECEITAS_FINANCIAMENTO_ENSINO", "OUTRAS_RECEITAS_DESTINADAS_EDUCACAO", "OUTRAS_RECEITAS_PARA_FINANCIAMENTO_DO_ENSINO"],
  "TOTAL": ["TOTAL", "TOTAL_OUTRAS_RECEITAS_DESTINADAS_ENSINO", "TOTAL_RECEITAS_ADICIONAIS_FINANCIAMENTO_ENSINO", "FIN_ENSINO_TOTAL_RECEITAS_ADICIONAIS", "TOTAL_DAS_RECEITAS_ADICIONAIS_PARA_FINANCIAMENTO_DO_ENSINO"]
};

export const mapMunicipalFundebFundefComposition = {
  "Contribuição na formação do Fundef/Fundeb – destinada": ["PARCELA_TRANSFERENCIAS_DESTINADAS_A_FORMACAO_DO_FUNDEF", "RECEITAS_DESTINADAS_AO_FUNDEB", "TOTAL_DESTINADO_FUNDEB", "TOTAL_DESTINADO_AO_FUNDEB"],
  "Receita recebida na redistribuição interna do Fundeb (Transferência de recursos do Fundeb)": ["TRANSFERENCIAS_DE_RECURSOS_DO_FUNDEF", "TRANSFERENCIAS_RECURSOS_FUNDEB", "TRANSFERENCIAS_DE_RECURSOS_DO_FUNDEB", "FUNDEB_PRINCIPAL_6_1_1", "FUNDEB_PRINCIPAL"],
  "Resultado Líquido (ganhos ou perdas = recebido - enviado)": ["RESULTADO_LIQUIDO", "RESULTADO_LIQUIDO_TRANSFERENCIAS_FUNDEB", "RESULTADO_LIQUIDO_DAS_TRANSFERENCIAS_DO_FUNDEB"],
  "Complementação da União": ["COMPLEMENTACAO_DA_UNIAO_AO_FUNDEF", "COMPLEMENTACAO_UNIAO_FUNDEB", "COMPLEMENTACAO_DA_UNIAO_AO_FUNDEB", "COMPLEMENTACAO_UNIAO"],
  "Receita da aplicação financeira do Fundeb": ["RECEITA_APLICACAO_FINANCEIRA_RECURSOS_FUNDEB", "RECEITA_DE_APLICACAO_FINANCEIRA_DOS_RECURSOS_DO_FUNDEB", "RECEITA_APLICACAO_FINANCEIRA"],
  "Ressarcimento de recursos do Fundeb": ["RESSARCIMENTO_RECURSOS_FUNDEB"],
  "Total do Fundeb": ["TOTAL_FUNDEB", "RECEITAS_RECEBIDAS_DO_FUNDEB", "RECEITAS_RECEBIDAS_FUNDEB", "TOTAL_DAS_RECEITAS_DO_FUNDEB_RECEBIDAS"]
}

export const mapComplementationFundebFundef = {
  "VAAF": ["COMPLEMENTACAO_DA_UNIAO_AO_FUNDEF", "COMPLEMENTACAO_UNIAO_FUNDEB", "COMPLEMENTACAO_DA_UNIAO_AO_FUNDEB", "FUNDEB_PRINCIPAL_6_2_1", "FUNDEB_VAAF_PRINCIPAL"],
  "VAAT": ["FUNDEB_PRINCIPAL_6_3_1", "FUNDEB_VAAT_PRINCIPAL"],
  "VAAR": ["FUNDEB_VAAR_PRINCIPAL"],
  "TOTAL": ["TOTAL"]
}

export const mapConstitutionalLimitMde = {
  "Valor exigido em MDE": ["VALOR_EXIGIDO_MDE", "IMPOSTOS_E_TRANSFERENCIAS_DESTINADAS_MDE", ""],
  "Valor aplicado em MDE": ["VALOR_APLICADO_MDE", "TOTAL_DE_DESPESAS_PARA_FINS_DE_LIMITE"],
  "% aplicado em MDE": ["MINIMO_DE_25_PORCENTO_DAS_RECEITAS_RESULTANTES_DE_IMPOSTOS", "MINIMO_DE_25_PORCENTO_DAS_RECEITAS_RESULTANTES_DE_IMPOSTOS_MDE", "PERCENTUAL_DE_APLICACAO_MDE_SOBRE_RECEITA_LIQUIDA_IMPOSTOS", "PERCENTUAL_APLICADO_MDE"]
}

export const mapExpensesBasicEducationFundeb = {
 "Despesas com profissionais da Educação básica": ["PAGAMENTO_PROFISSIONAIS_MAGISTERIO_DO_ENSINO_FUNDAMENTAL", "FUNDEB_PAGAMENTO_PROFISSIONAIS_MAGISTERIO", "DESPESAS_PROFISSIONAIS_EDUCACAO"],
 "% aplicado com profissionais da Educação Básica": ["MINIMO_60_PORCENTO_DO_FUNDEF_NA_REMUNERACAO_ENSINO_FUNDAMENTAL", "MINIMO_60_PORCENTO_FUNDEB_REMUNERACAO_MAGISTERIO_EDUCACAO", "PERCENTUAL_APLICADO_PROFISSIONAIS_EDUCACAO", "MINIMO_60_PORCENTO_FUNDEB_REMUNERACAO_MAGISTERIO", "PERCENTUAL_APLICADO_MDE"],
}

export const mapAreasActivityExpense = {
  "Educação Infantil": ["EDUCACAO_INFANTIL", "MDE_EDUCACAO_INFANTIL", "MDE_DESPESAS_EDUCACAO_INFANTIL"],
  "Creche": ["CRECHE", "MDE_DESPESAS_CRECHE", "MDE_DESPESAS_EDUCACAO_INFANTIL_CRECHE", "MDE_COM_RECEITAS_IMPOSTOS_FUNDEB_EDUCACAO_INFANTIL_CRECHE"],
  "Pré-escola": ["PRE_ESCOLA", "MDE_DESPESAS_EDUCACAO_INFANTIL_PRE_ESCOLA", "MDE_DESPESAS_PRE_ESCOLA", "MDE_COM_RECEITAS_IMPOSTOS_FUNDEB_EDUCACAO_INFANTIL_PRE_ESCOLA"],
  "Ensino Fundamental": ["ENSINO_FUNDAMENTAL", "MDE_ENSINO_FUNDAMENTAL", "MDE_DESPESAS_ENSINO_FUNDAMENTAL"],
  "Ensino Médio": ["OUTRAS_DESPESAS_ENSINO_MEDIO", "MDE_DESPESAS_ENSINO_MEDIO", "ENSINO_MEDIO", "TOTAL_OUTRAS_DESPESAS_COM_EDUCACAO_ENSINO_MEDIO"],
  "Ensino Superior": ["ENSINO_SUPERIOR", "MDE_DESPESAS_ENSINO_SUPERIOR", "OUTRAS_DESPESAS_ENSINO_SUPERIOR", "TOTAL_OUTRAS_DESPESAS_COM_EDUCACAO_ENSINO_SUPERIOR"],
  "Educação Especial": ["EDUCACAO_ESPECIAL", "TOTAL_OUTRAS_DESPESAS_COM_EDUCACAO_ESPECIAL"],
  "Educação Jovens e Adultos": ["EDUCACAO_DE_JOVENS_E_ADULTOS", "TOTAL_OUTRAS_DESPESAS_COM_EDUCACAO_DE_JOVENS_E_ADULTOS"],
  "Ensino Profissional não integrado ao ensino regular": ["OUTRAS_DESPESAS_ENSINO_PROFISSIONAL_NAO_INTEGRADO", "MDE_DESPESAS_ENSINO_PROFISSIONAL_NAO_INTEGRADO_ENSINO_REGULAR", "ENSINO_PROFISSIONAL", "TOTAL_OUTRAS_DESPESAS_COM_EDUCACAO_ENSINO_PROFISSIONAL"],
  "Outras": ["OUTRAS_SUBFUNCOES", "MDE_OUTRAS_DESPESAS", "TOTAL_OUTRAS_DESPESAS_COM_EDUCACAO_OUTRAS"],
  "TOTAL despesas típicas com MDE": ["TOTAL", "MDE_TOTAL_DESPESAS_ACOES_TIPICAS", "TOTAL_DESPESAS_COM_ACOES_TIPICAS_MDE", "TOTAL_DAS_DESPESAS_COM_ENSINO"]
}


export const mapBasicEducationMinimalPotential = {
  "Receita Líquida de impostos e transferência constitucionais e legais MDE": ["RECEITA_LIQUIDA_IMPOSTOS_MDE", "IMPOSTOS_E_TRANSFERENCIAS_DESTINADAS_MDE", "APLICACAO_EM_MDE_SOBRE_RECEITA_DE_IMPOSTOS", "APLICACAO_EM_MDE_SOBRE_RECEITA_LIQUIDA_DE_IMPOSTOS", "APLICACAO_EM_MDE_SOBRE_RECEITA_LIQUIDA_DE_IMPOSTOS"],
  "Receitas destinadas ao Fundeb (fundo estadual)": ["PARCELA_TRANSFERENCIAS_DESTINADAS_A_FORMACAO_DO_FUNDEF", "RECEITAS_DESTINADAS_AO_FUNDEB", "TOTAL_DESTINADO_FUNDEB", "TOTAL_DESTINADO_AO_FUNDEB"],
  "receitas recebidas do Fundeb (fundo estadual)": ["TRANSFERENCIAS_DE_RECURSOS_DO_FUNDEF", "TRANSFERENCIAS_RECURSOS_FUNDEB", "TRANSFERENCIAS_RECURSOS_FUNDEB", "TRANSFERENCIAS_DE_RECURSOS_DO_FUNDEB", "FUNDEB_PRINCIPAL_6_1_1", "FUNDEB_PRINCIPAL"],
  "Complementação da União ao Fundeb": ["COMPLEMENTACAO_DA_UNIAO_AO_FUNDEF", "COMPLEMENTACAO_UNIAO_FUNDEB", "COMPLEMENTACAO_DA_UNIAO_AO_FUNDEB"],
  "Quota do salário-educação": ["TRANSFERENCIAS_DO_SALARIO_EDUCACAO", "TRANSFERENCIAS_SALARIO_EDUCACAO", "FIN_ENSINO_SALARIO_EDUCACAO", "RECEITA_DE_TRANSFERENCIAS_DO_FNDE_SALARIO_EDUCACAO"],
  "Transferência de Programas do FNDE (PDDE, PNAE, PNATE, PNLD)": ["OUTRAS_TRANSFERENCIAS_DO_FNDE", "OUTRAS_TRANSFERENCIAS_FNDE"],
  "Royalties do Petróleo e gás": ["RECEITA_DE_ROYALTIES_DESTINADOS_A_EDUCACAO", "FIN_ENSINO_RECEITA_ROYALTIES_DESTINADOS_EDUCACAO"],
  "TOTAL": ["TOTAL"]
}

const standardizeType = (type, map) => {
  for (const [standardType, types] of Object.entries(map)) {
    if (types.includes(type)) {
      return standardType;
    }
  }
  return type;
};

export const standardizeTypeOwnRevenues = (type) => standardizeType(type, mapOwnRevenues);
export const standardizedTypeConstitutionalTransfersRevenue = (type) => standardizeType(type, mapConstitutionalTransfersRevenue)
export const standardizeTypeMunicipalTaxesRevenues = (type) => standardizeType(type, mapMunicipalTaxesRevenues);
export const standardizeTypeAdditionalEducationRevenues = (type) => standardizeType(type, mapAdditionalMunicipalEducationRevenue);
export const standardizedTypeMunicipalFundebFundefComposition = (type) => standardizeType(type, mapMunicipalFundebFundefComposition)
export const standardizedTypeComplementationFundebFundef = (type) => standardizeType(type, mapComplementationFundebFundef)
export const standardizedTypeConstitutionalLimitMde = (type) => standardizeType(type, mapConstitutionalLimitMde)
export const standardizedTypeExpensesBasicEducationFundeb = (type) => standardizeType(type, mapExpensesBasicEducationFundeb)
export const standardizedTypeAreasActivityExpense = (type) => standardizeType(type, mapAreasActivityExpense)
export const standardizedTypeBasicEducationMinimalPotential = (type) => standardizeType(type, mapBasicEducationMinimalPotential)
